import { Patient, Appointment, Doctor, QueueItem, Bill, Prescription, UserAccount, SystemNotification, SupportTicket } from './types';

export const mockSupportTickets: SupportTicket[] = [
  {
    id: 'TKT-1001',
    subject: 'Cannot login with doctor account on mobile station',
    category: 'Login Problem',
    createdDate: '25/09/2023',
    priority: 'High',
    status: 'Resolved',
    lastUpdated: '26/09/2023'
  },
  {
    id: 'TKT-1002',
    subject: 'Error when saving prescription with custom compounding note',
    category: 'Prescription Problem',
    createdDate: '01/10/2023',
    priority: 'Urgent',
    status: 'In Progress',
    lastUpdated: '02/10/2023'
  },
  {
    id: 'TKT-1003',
    subject: 'Request for thermal invoice printer calibration in OPD Counter 2',
    category: 'Billing Problem',
    createdDate: '02/10/2023',
    priority: 'Medium',
    status: 'Open',
    lastUpdated: '02/10/2023'
  },
  {
    id: 'TKT-1004',
    subject: 'Add new antibiotic molecule (Faropenem 200mg) to dispensary catalogue',
    category: 'Technical Issue',
    createdDate: '03/10/2023',
    priority: 'Low',
    status: 'Resolved',
    lastUpdated: '03/10/2023'
  },
  {
    id: 'TKT-1005',
    subject: 'NABH audit trail export timeout on quarterly reporting module',
    category: 'Report Problem',
    createdDate: '04/10/2023',
    priority: 'High',
    status: 'In Progress',
    lastUpdated: '04/10/2023'
  },
  {
    id: 'TKT-1006',
    subject: 'Configure SMS gateway template for follow-up reminders',
    category: 'Appointment Problem',
    createdDate: '05/10/2023',
    priority: 'Medium',
    status: 'Open',
    lastUpdated: '05/10/2023'
  }
];

export const mockDoctors: Doctor[] = [
  {
    id: 'D-101',
    name: 'Dr. Sarah Chen',
    specialization: 'General Physician',
    qualification: 'MD, MBBS (Gold Medalist)',
    experience: '12 Years',
    availability: 'Mon, Wed, Fri',
    image: '/src/assets/images/doctor_female_professional_1790961100983.jpg',
    status: 'Active',
    phone: '+91 98765-11111',
    email: 'sarah.chen@medflow.com',
    registrationNumber: 'MCI-98442-KA',
    consultationFee: 500.00,
    workingDays: ['Monday', 'Wednesday', 'Friday'],
    workingHours: '09:00 AM - 05:00 PM',
    appointmentDuration: 20
  },
  {
    id: 'D-102',
    name: 'Dr. Michael Roberts',
    specialization: 'Cardiologist',
    qualification: 'MD, DM (Cardiology), FACC',
    experience: '15 Years',
    availability: 'Tue, Thu, Sat',
    image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&h=400&fit=crop',
    status: 'Active',
    phone: '+91 98765-22222',
    email: 'michael.r@medflow.com',
    registrationNumber: 'MCI-77112-DEL',
    consultationFee: 1500.00,
    workingDays: ['Tuesday', 'Thursday', 'Saturday'],
    workingHours: '10:00 AM - 06:00 PM',
    appointmentDuration: 30
  },
  {
    id: 'D-103',
    name: 'Dr. Ananya Iyer',
    specialization: 'Pediatrician',
    qualification: 'MBBS, DCH, DNB (Pediatrics)',
    experience: '9 Years',
    availability: 'Mon, Tue, Wed, Thu, Fri',
    image: 'https://images.unsplash.com/photo-1594824813589-3221a71e2043?w=400&h=400&fit=crop',
    status: 'Active',
    phone: '+91 98765-33333',
    email: 'ananya.iyer@medflow.com',
    registrationNumber: 'MCI-55421-TN',
    consultationFee: 700.00,
    workingDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    workingHours: '08:30 AM - 03:30 PM',
    appointmentDuration: 20
  },
  {
    id: 'D-104',
    name: 'Dr. Vikram Malhotra',
    specialization: 'Orthopedic Surgeon',
    qualification: 'MS (Orthopedics), M.Ch (Joint Replacement)',
    experience: '18 Years',
    availability: 'Wed, Fri, Sat',
    image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&h=400&fit=crop',
    status: 'Active',
    phone: '+91 98765-44444',
    email: 'vikram.m@medflow.com',
    registrationNumber: 'MCI-33291-MH',
    consultationFee: 1200.00,
    workingDays: ['Wednesday', 'Friday', 'Saturday'],
    workingHours: '11:00 AM - 07:00 PM',
    appointmentDuration: 25
  },
  {
    id: 'D-105',
    name: 'Dr. Neha Kapoor',
    specialization: 'Dermatologist & Cosmetologist',
    qualification: 'MD (Dermatology, Venereology & Leprosy)',
    experience: '8 Years',
    availability: 'Mon, Thu, Sat',
    image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=400&fit=crop',
    status: 'Active',
    phone: '+91 98765-55555',
    email: 'neha.kapoor@medflow.com',
    registrationNumber: 'MCI-88129-KA',
    consultationFee: 800.00,
    workingDays: ['Monday', 'Thursday', 'Saturday'],
    workingHours: '10:00 AM - 04:30 PM',
    appointmentDuration: 20
  },
  {
    id: 'D-106',
    name: 'Dr. Rajesh Deshmukh',
    specialization: 'Neurologist',
    qualification: 'MD (Medicine), DM (Neurology)',
    experience: '14 Years',
    availability: 'Tue, Fri',
    image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400&h=400&fit=crop',
    status: 'Away',
    phone: '+91 98765-66666',
    email: 'rajesh.d@medflow.com',
    registrationNumber: 'MCI-66219-MH',
    consultationFee: 1800.00,
    workingDays: ['Tuesday', 'Friday'],
    workingHours: '01:00 PM - 08:00 PM',
    appointmentDuration: 30
  }
];

export const mockUsers: UserAccount[] = [
  {
    id: 'U-001',
    name: 'John Smith',
    username: 'jsmith_admin',
    role: 'Administrator',
    password: 'admin123',
    phone: '+91 98765-43210',
    email: 'admin@medflow.com',
    status: 'Active',
    lastLogin: '30/10/2023 08:30 AM',
    department: 'Hospital Administration',
    shift: 'General (09:00 AM - 06:00 PM)',
    employeeId: 'EMP-0101',
    qualification: 'MHA, B.Tech',
    twoFactorEnabled: true,
    accessLevel: 'Super Admin',
    joinedDate: '15/01/2021',
    emergencyContact: '+91 98765-00112'
  },
  {
    id: 'U-002',
    name: 'Emma Watson',
    username: 'ewatson_rec',
    role: 'Receptionist',
    password: 'reception123',
    phone: '+91 98765-12345',
    email: 'emma@medflow.com',
    status: 'Active',
    lastLogin: '30/10/2023 09:15 AM',
    department: 'Front Desk & OPD Registration',
    shift: 'Morning (08:00 AM - 04:00 PM)',
    employeeId: 'EMP-0204',
    qualification: 'B.Sc Healthcare Administration',
    twoFactorEnabled: true,
    accessLevel: 'Front Desk',
    joinedDate: '01/06/2022',
    emergencyContact: '+91 98765-33441'
  },
  {
    id: 'U-003',
    name: 'Dr. Sarah Chen',
    username: 'schen_md',
    role: 'Doctor',
    password: 'doctor123',
    phone: '+91 98765-11111',
    email: 'sarah.chen@medflow.com',
    status: 'Active',
    lastLogin: '30/10/2023 08:45 AM',
    department: 'General Medicine & OPD',
    shift: 'Morning (09:00 AM - 05:00 PM)',
    employeeId: 'EMP-0301',
    qualification: 'MD, MBBS (Gold Medalist)',
    registrationNumber: 'MCI-98442-KA',
    twoFactorEnabled: true,
    accessLevel: 'Clinical Access',
    joinedDate: '10/03/2019',
    emergencyContact: '+91 98765-88990'
  },
  {
    id: 'U-004',
    name: 'Dr. Michael Roberts',
    username: 'mroberts_cardio',
    role: 'Doctor',
    password: 'doctor123',
    phone: '+91 98765-22222',
    email: 'michael.r@medflow.com',
    status: 'Active',
    lastLogin: '29/10/2023 04:20 PM',
    department: 'Cardiology & Intensive Care',
    shift: 'Rotational (10:00 AM - 06:00 PM)',
    employeeId: 'EMP-0302',
    qualification: 'MD, DM Cardiology, FACC',
    registrationNumber: 'MCI-77112-DEL',
    twoFactorEnabled: true,
    accessLevel: 'Clinical Access',
    joinedDate: '12/08/2020',
    emergencyContact: '+91 98765-44221'
  },
  {
    id: 'U-005',
    name: 'Rajesh Sharma',
    username: 'rsharma_fin',
    role: 'Accountant',
    password: 'accounts123',
    phone: '+91 98765-55443',
    email: 'accounts@medflow.com',
    status: 'Active',
    lastLogin: '30/10/2023 10:05 AM',
    department: 'Billing & Insurance Claims',
    shift: 'Day Shift (09:30 AM - 06:30 PM)',
    employeeId: 'EMP-0401',
    qualification: 'Chartered Accountant (CA), B.Com',
    twoFactorEnabled: true,
    accessLevel: 'Financial Access',
    joinedDate: '01/02/2021',
    emergencyContact: '+91 98765-77881'
  },
  {
    id: 'U-006',
    name: 'Priya Sundaram',
    username: 'psundaram_nurse',
    role: 'Staff',
    password: 'nurse123',
    phone: '+91 98765-66778',
    email: 'priya.s@medflow.com',
    status: 'Active',
    lastLogin: '30/10/2023 07:55 AM',
    department: 'Nursing & Triage Station',
    shift: 'Morning Shift (07:30 AM - 03:30 PM)',
    employeeId: 'EMP-0501',
    qualification: 'B.Sc Nursing, Critical Care Cert.',
    registrationNumber: 'INC-RN-44321',
    twoFactorEnabled: false,
    accessLevel: 'Clinical Access',
    joinedDate: '15/09/2022',
    emergencyContact: '+91 98765-99002'
  },
  {
    id: 'U-007',
    name: 'Anand Verma',
    username: 'averma_pharm',
    role: 'Staff',
    password: 'pharm123',
    phone: '+91 98765-33221',
    email: 'anand.v@medflow.com',
    status: 'On Leave',
    lastLogin: '25/10/2023 06:10 PM',
    department: 'In-House Pharmacy & Dispensing',
    shift: 'Evening Shift (02:00 PM - 10:00 PM)',
    employeeId: 'EMP-0502',
    qualification: 'B.Pharm, D.Pharm',
    registrationNumber: 'PCI-KA-11883',
    twoFactorEnabled: true,
    accessLevel: 'Restricted',
    joinedDate: '05/04/2023',
    emergencyContact: '+91 98765-11223'
  },
  {
    id: 'U-008',
    name: 'Devika Nair',
    username: 'dnair_rec',
    role: 'Receptionist',
    password: 'reception123',
    phone: '+91 98765-88776',
    email: 'devika.n@medflow.com',
    status: 'Active',
    lastLogin: '30/10/2023 01:15 PM',
    department: 'Front Desk & OPD Registration',
    shift: 'Afternoon Shift (01:00 PM - 09:00 PM)',
    employeeId: 'EMP-0205',
    qualification: 'Diploma in Hospital PR',
    twoFactorEnabled: true,
    accessLevel: 'Front Desk',
    joinedDate: '10/11/2023',
    emergencyContact: '+91 98765-55667'
  },
  {
    id: 'U-009',
    name: 'Kavita Reddy',
    username: 'kreddy_lab',
    role: 'Staff',
    password: 'staff123',
    phone: '+91 98765-77112',
    email: 'kavita.r@medflow.com',
    status: 'Active',
    lastLogin: '30/10/2023 08:10 AM',
    department: 'Pathology & Diagnostic Laboratory',
    shift: 'General (08:30 AM - 05:00 PM)',
    employeeId: 'EMP-0503',
    qualification: 'M.Sc Medical Lab Technology (MLT)',
    twoFactorEnabled: true,
    accessLevel: 'Clinical Access',
    joinedDate: '12/03/2022',
    emergencyContact: '+91 98765-88110'
  }
];

export const mockNotifications: SystemNotification[] = [
  {
    id: 'N-001',
    title: 'New Appointment Booked',
    message: 'John Anderson (P-1001) has booked a Routine Check-up with Dr. Sarah Chen for 30/10/2023 at 10:30 AM.',
    type: 'appointment_booked',
    status: 'Unread',
    timestamp: '30/10/2023 08:45 AM'
  },
  {
    id: 'N-002',
    title: 'Payment Received',
    message: 'Payment of ₹24,150.50 received via Card for Invoice #INV-2023-001.',
    type: 'payment_received',
    status: 'Read',
    timestamp: '30/10/2023 11:00 AM'
  },
  {
    id: 'N-003',
    title: 'Critical Lab Alert',
    message: 'High Fasting Blood Sugar (265 mg/dL) recorded for Robert Wilson (P-1003). Review requested.',
    type: 'patient_registered',
    status: 'Unread',
    timestamp: '30/10/2023 09:15 AM'
  },
  {
    id: 'N-004',
    title: 'Emergency Patient Queued',
    message: 'Kavita Menon (P-1008) admitted to OPD Triage with priority Emergency.',
    type: 'appointment_booked',
    status: 'Unread',
    timestamp: '30/10/2023 09:50 AM'
  },
  {
    id: 'N-005',
    title: 'Follow-up Reminder',
    message: 'Emily Davis (P-1006) is due for pediatric vaccination review in 2 days.',
    type: 'followup_reminder',
    status: 'Unread',
    timestamp: '30/10/2023 07:00 AM'
  },
  {
    id: 'N-006',
    title: 'Pharmacy Stock Warning',
    message: 'Amoxicillin 250mg capsules reached threshold level (15 strips remaining).',
    type: 'appointment_cancelled',
    status: 'Read',
    timestamp: '29/10/2023 05:30 PM'
  },
  {
    id: 'N-007',
    title: 'New Patient Intake',
    message: 'New outpatient Arjun Patel (P-1007) registered at Front Desk Counter 1.',
    type: 'patient_registered',
    status: 'Read',
    timestamp: '29/10/2023 04:30 PM'
  },
  {
    id: 'N-008',
    title: 'NABH Audit Backup Completed',
    message: 'Daily encrypted backup and audit log hash successfully archived.',
    type: 'payment_received',
    status: 'Read',
    timestamp: '29/10/2023 11:59 PM'
  }
];

export const mockPatients: Patient[] = [
  {
    id: 'P-1001',
    name: 'John Anderson',
    age: 45,
    gender: 'Male',
    phone: '+91 99887-76655',
    email: 'john.a@example.com',
    lastVisit: '30/09/2023',
    status: 'Active',
    bloodGroup: 'O+',
    address: '123 MG Road, Indiranagar, Bangalore, KA',
    allergies: 'None recorded',
    emergencyContact: 'Jane Anderson (+91 99887-55443)',
    insuranceProvider: 'Star Health Allied Insurance',
    insuranceNumber: 'SH-998877-22'
  },
  {
    id: 'P-1002',
    name: 'Sarah Miller',
    age: 32,
    gender: 'Female',
    phone: '+91 88776-65544',
    email: 'sarah.m@example.com',
    lastVisit: '20/09/2023',
    status: 'Active',
    bloodGroup: 'A-',
    address: '456 Residency Road, Richmond Town, Bangalore, KA',
    allergies: 'Penicillin, Dust mites',
    emergencyContact: 'Robert Miller (+91 88776-44332)',
    insuranceProvider: 'ICICI Lombard Health',
    insuranceNumber: 'IL-112233-89'
  },
  {
    id: 'P-1003',
    name: 'Robert Wilson',
    age: 58,
    gender: 'Male',
    phone: '+91 98112-33445',
    email: 'robert.w@example.com',
    lastVisit: '28/09/2023',
    status: 'Active',
    bloodGroup: 'B+',
    address: '78 Palm Avenue, Koramangala 4th Block, Bangalore, KA',
    allergies: 'Sulfa Drugs',
    emergencyContact: 'Mary Wilson (+91 98112-33446)',
    insuranceProvider: 'HDFC ERGO Health',
    insuranceNumber: 'HE-778899-01'
  },
  {
    id: 'P-1004',
    name: 'Michael Brown',
    age: 28,
    gender: 'Male',
    phone: '+91 97441-22334',
    email: 'michael.b@example.com',
    lastVisit: '25/09/2023',
    status: 'Active',
    bloodGroup: 'AB+',
    address: '12 Green Glen Layout, Bellandur, Bangalore, KA',
    allergies: 'None recorded',
    emergencyContact: 'Anita Brown (+91 97441-22335)',
    insuranceProvider: 'Max Bupa Health',
    insuranceNumber: 'MB-445566-77'
  },
  {
    id: 'P-1005',
    name: 'Jane Doe',
    age: 64,
    gender: 'Female',
    phone: '+91 96554-11223',
    email: 'jane.doe@example.com',
    lastVisit: '10/09/2023',
    status: 'Active',
    bloodGroup: 'O-',
    address: '55 Cunningham Road, Vasanth Nagar, Bangalore, KA',
    allergies: 'Aspirin, NSAIDs',
    emergencyContact: 'David Doe (+91 96554-11224)',
    insuranceProvider: 'Care Health Insurance',
    insuranceNumber: 'CH-332211-55'
  },
  {
    id: 'P-1006',
    name: 'Emily Davis',
    age: 7,
    gender: 'Female',
    phone: '+91 95443-88990',
    email: 'emily.parents@example.com',
    lastVisit: '29/09/2023',
    status: 'Active',
    bloodGroup: 'B-',
    address: '89 Lavelle Road, Shanthala Nagar, Bangalore, KA',
    allergies: 'Peanuts, Egg Protein',
    emergencyContact: 'Catherine Davis (Mother: +91 95443-88991)',
    insuranceProvider: 'Star Health Comprehensive',
    insuranceNumber: 'SH-884411-90'
  },
  {
    id: 'P-1007',
    name: 'Arjun Patel',
    age: 39,
    gender: 'Male',
    phone: '+91 98223-44556',
    email: 'arjun.patel@example.com',
    lastVisit: '01/10/2023',
    status: 'Active',
    bloodGroup: 'A+',
    address: '34 Outer Ring Road, Marathahalli, Bangalore, KA',
    allergies: 'None recorded',
    emergencyContact: 'Pooja Patel (+91 98223-44557)',
    insuranceProvider: 'Bajaj Allianz General',
    insuranceNumber: 'BA-991122-44'
  },
  {
    id: 'P-1008',
    name: 'Kavita Menon',
    age: 51,
    gender: 'Female',
    phone: '+91 97110-88992',
    email: 'kavita.m@example.com',
    lastVisit: '02/10/2023',
    status: 'Active',
    bloodGroup: 'AB-',
    address: '102 100ft Road, HAL 2nd Stage, Bangalore, KA',
    allergies: 'Ciprofloxacin',
    emergencyContact: 'Suresh Menon (+91 97110-88993)',
    insuranceProvider: 'Niva Bupa Health',
    insuranceNumber: 'NB-667788-12'
  },
  {
    id: 'P-1009',
    name: 'Ramesh Kumar',
    age: 62,
    gender: 'Male',
    phone: '+91 98334-55667',
    email: 'ramesh.kumar@example.com',
    lastVisit: '18/09/2023',
    status: 'Active',
    bloodGroup: 'O+',
    address: '42 Bannerghatta Road, Jayanagar 9th Block, Bangalore, KA',
    allergies: 'None recorded',
    emergencyContact: 'Sunita Kumar (+91 98334-55668)',
    insuranceProvider: 'Senior Citizen Red Carpet',
    insuranceNumber: 'SC-113355-88'
  },
  {
    id: 'P-1010',
    name: 'Ananya Sharma',
    age: 24,
    gender: 'Female',
    phone: '+91 99112-77889',
    email: 'ananya.s@example.com',
    lastVisit: '27/09/2023',
    status: 'Active',
    bloodGroup: 'B+',
    address: '16 CMH Road, Ulsoor, Bangalore, KA',
    allergies: 'Latex',
    emergencyContact: 'Deepak Sharma (+91 99112-77880)',
    insuranceProvider: 'Tata AIG Medicare',
    insuranceNumber: 'TA-554433-21'
  },
  {
    id: 'P-1011',
    name: 'Devraj Sengupta',
    age: 41,
    gender: 'Male',
    phone: '+91 98440-11229',
    email: 'devraj.s@example.com',
    lastVisit: '12/08/2023',
    status: 'Inactive',
    bloodGroup: 'A+',
    address: '77 Sarjapur Main Road, HSR Layout, Bangalore, KA',
    allergies: 'None recorded',
    emergencyContact: 'Rina Sengupta (+91 98440-11230)',
    insuranceProvider: 'Universal Sompo',
    insuranceNumber: 'US-778811-00'
  },
  {
    id: 'P-1012',
    name: 'Meenakshi Sundaram',
    age: 36,
    gender: 'Female',
    phone: '+91 97331-44552',
    email: 'meenakshi.s@example.com',
    lastVisit: '03/10/2023',
    status: 'Active',
    bloodGroup: 'O+',
    address: '29 Malleshwaram 8th Cross, Bangalore, KA',
    allergies: 'Ibuprofen',
    emergencyContact: 'Sundaram K (+91 97331-44553)',
    insuranceProvider: 'Religare Health',
    insuranceNumber: 'RH-224466-99'
  }
];

export const mockAppointments: Appointment[] = [
  {
    id: 'A-5001',
    patientId: 'P-1001',
    patientName: 'John Anderson',
    doctorId: 'D-101',
    doctorName: 'Dr. Sarah Chen',
    date: '30/10/2023',
    time: '09:30 AM',
    status: 'Completed',
    reason: 'Routine Check-up & BP Monitoring',
    type: 'Routine Check-up',
    priority: 'Normal',
    paymentStatus: 'Paid',
    notes: 'Blood pressure stable at 128/82. Advised low sodium diet.'
  },
  {
    id: 'A-5002',
    patientId: 'P-1002',
    patientName: 'Sarah Miller',
    doctorId: 'D-101',
    doctorName: 'Dr. Sarah Chen',
    date: '30/10/2023',
    time: '10:00 AM',
    status: 'In Consultation',
    reason: 'Seasonal Allergic Rhinitis Follow-up',
    type: 'Follow-up',
    priority: 'Urgent',
    paymentStatus: 'Paid',
    notes: 'Nasal congestion improved with antihistamines.'
  },
  {
    id: 'A-5003',
    patientId: 'P-1003',
    patientName: 'Robert Wilson',
    doctorId: 'D-102',
    doctorName: 'Dr. Michael Roberts',
    date: '30/10/2023',
    time: '10:30 AM',
    status: 'Scheduled',
    reason: 'Post-Stent Cardiac Check & ECG Review',
    type: 'New Consultation',
    priority: 'Urgent',
    paymentStatus: 'Paid',
    notes: 'Carry previous angiography and lipid profile reports.'
  },
  {
    id: 'A-5004',
    patientId: 'P-1006',
    patientName: 'Emily Davis',
    doctorId: 'D-103',
    doctorName: 'Dr. Ananya Iyer',
    date: '30/10/2023',
    time: '11:15 AM',
    status: 'Scheduled',
    reason: 'Pediatric Viral Fever & Cough x 2 Days',
    type: 'New Consultation',
    priority: 'Normal',
    paymentStatus: 'Unpaid',
    notes: 'Temperature recorded at 100.4°F at triage.'
  },
  {
    id: 'A-5005',
    patientId: 'P-1004',
    patientName: 'Michael Brown',
    doctorId: 'D-104',
    doctorName: 'Dr. Vikram Malhotra',
    date: '30/10/2023',
    time: '11:45 AM',
    status: 'Scheduled',
    reason: 'Right Knee Sports Ligament Strain',
    type: 'New Consultation',
    priority: 'Normal',
    paymentStatus: 'Paid',
    notes: 'MRI scan reports attached.'
  },
  {
    id: 'A-5006',
    patientId: 'P-1008',
    patientName: 'Kavita Menon',
    doctorId: 'D-102',
    doctorName: 'Dr. Michael Roberts',
    date: '30/10/2023',
    time: '12:30 PM',
    status: 'Scheduled',
    reason: 'Sudden Palpitations & Dizziness',
    type: 'Emergency',
    priority: 'Emergency',
    paymentStatus: 'Paid',
    notes: 'Triage ECG performed immediately upon arrival.'
  },
  {
    id: 'A-5007',
    patientId: 'P-1007',
    patientName: 'Arjun Patel',
    doctorId: 'D-105',
    doctorName: 'Dr. Neha Kapoor',
    date: '31/10/2023',
    time: '10:00 AM',
    status: 'Scheduled',
    reason: 'Contact Dermatitis & Skin Rash',
    type: 'New Consultation',
    priority: 'Normal',
    paymentStatus: 'Unpaid'
  },
  {
    id: 'A-5008',
    patientId: 'P-1009',
    patientName: 'Ramesh Kumar',
    doctorId: 'D-101',
    doctorName: 'Dr. Sarah Chen',
    date: '31/10/2023',
    time: '10:45 AM',
    status: 'Scheduled',
    reason: 'Type 2 Diabetes Quarterly Review',
    type: 'Follow-up',
    priority: 'Normal',
    paymentStatus: 'Paid'
  },
  {
    id: 'A-5009',
    patientId: 'P-1010',
    patientName: 'Ananya Sharma',
    doctorId: 'D-106',
    doctorName: 'Dr. Rajesh Deshmukh',
    date: '31/10/2023',
    time: '02:00 PM',
    status: 'Scheduled',
    reason: 'Chronic Migraine with Visual Aura',
    type: 'New Consultation',
    priority: 'Urgent',
    paymentStatus: 'Paid'
  },
  {
    id: 'A-5010',
    patientId: 'P-1005',
    patientName: 'Jane Doe',
    doctorId: 'D-104',
    doctorName: 'Dr. Vikram Malhotra',
    date: '29/10/2023',
    time: '04:00 PM',
    status: 'Completed',
    reason: 'Bilateral Osteoarthritis Knee Follow-up',
    type: 'Follow-up',
    priority: 'Normal',
    paymentStatus: 'Paid',
    notes: 'Prescribed joint strengthening physiotherapy.'
  },
  {
    id: 'A-5011',
    patientId: 'P-1011',
    patientName: 'Devraj Sengupta',
    doctorId: 'D-101',
    doctorName: 'Dr. Sarah Chen',
    date: '28/10/2023',
    time: '03:15 PM',
    status: 'Cancelled',
    reason: 'Out of town on emergency travel',
    type: 'Routine Check-up',
    priority: 'Normal',
    paymentStatus: 'Unpaid'
  },
  {
    id: 'A-5012',
    patientId: 'P-1012',
    patientName: 'Meenakshi Sundaram',
    doctorId: 'D-105',
    doctorName: 'Dr. Neha Kapoor',
    date: '29/10/2023',
    time: '11:00 AM',
    status: 'Completed',
    reason: 'Acne Vulgaris Treatment Session',
    type: 'New Consultation',
    priority: 'Normal',
    paymentStatus: 'Paid'
  }
];

export const mockQueue: QueueItem[] = [
  {
    id: 'Q-001',
    patientId: 'P-1001',
    patientName: 'John Anderson',
    appointmentId: 'A-5001',
    queueNumber: '01',
    doctorName: 'Dr. Sarah Chen',
    waitingTime: '15 mins',
    priority: 'Normal',
    status: 'Waiting'
  },
  {
    id: 'Q-002',
    patientId: 'P-1002',
    patientName: 'Sarah Miller',
    appointmentId: 'A-5002',
    queueNumber: '02',
    doctorName: 'Dr. Sarah Chen',
    waitingTime: '5 mins',
    priority: 'Urgent',
    status: 'In Consultation'
  },
  {
    id: 'Q-003',
    patientId: 'P-1003',
    patientName: 'Robert Wilson',
    appointmentId: 'A-5003',
    queueNumber: '03',
    doctorName: 'Dr. Michael Roberts',
    waitingTime: '25 mins',
    priority: 'Urgent',
    status: 'Waiting'
  },
  {
    id: 'Q-004',
    patientId: 'P-1006',
    patientName: 'Emily Davis',
    appointmentId: 'A-5004',
    queueNumber: '04',
    doctorName: 'Dr. Ananya Iyer',
    waitingTime: '10 mins',
    priority: 'Normal',
    status: 'Waiting'
  },
  {
    id: 'Q-005',
    patientId: 'P-1004',
    patientName: 'Michael Brown',
    appointmentId: 'A-5005',
    queueNumber: '05',
    doctorName: 'Dr. Vikram Malhotra',
    waitingTime: '2 mins',
    priority: 'Normal',
    status: 'Waiting'
  },
  {
    id: 'Q-006',
    patientId: 'P-1008',
    patientName: 'Kavita Menon',
    appointmentId: 'A-5006',
    queueNumber: '06',
    doctorName: 'Dr. Michael Roberts',
    waitingTime: 'Just Now',
    priority: 'Emergency',
    status: 'Waiting'
  }
];

export const mockBills: Bill[] = [
  {
    id: 'INV-2023-001',
    patientId: 'P-1001',
    patientName: 'John Anderson',
    date: '30/10/2023',
    amount: 23000.00,
    status: 'Paid',
    items: [
      { description: 'Executive Health Checkup Package', price: 18000.00, quantity: 1 },
      { description: 'Complete Blood Count (CBC) & ESR', price: 450.00, quantity: 1 },
      { description: 'Lipid Profile Extended Panel', price: 750.00, quantity: 1 },
      { description: 'Cardiology Consultation Fee (Specialist)', price: 1500.00, quantity: 1 },
      { description: 'Standard 12-Lead ECG / EKG', price: 600.00, quantity: 1 },
      { description: 'Fast-Track OPD Registration Fee', price: 1700.00, quantity: 1 }
    ],
    tax: 1150.50,
    discount: 0,
    total: 24150.50
  },
  {
    id: 'INV-2023-002',
    patientId: 'P-1002',
    patientName: 'Sarah Miller',
    date: '29/10/2023',
    amount: 1142.86,
    status: 'Paid',
    items: [
      { description: 'General Physician Consultation Fee', price: 500.00, quantity: 1 },
      { description: 'Skin Prick Allergy Test Screening', price: 642.86, quantity: 1 }
    ],
    tax: 57.14,
    discount: 0,
    total: 1200.00
  },
  {
    id: 'INV-2023-003',
    patientId: 'P-1003',
    patientName: 'Robert Wilson',
    date: '29/10/2023',
    amount: 5238.10,
    status: 'Paid',
    items: [
      { description: 'Cardiology Specialist Consultation', price: 1500.00, quantity: 1 },
      { description: '2D Echocardiography (Echo)', price: 2500.00, quantity: 1 },
      { description: 'High-Sensitivity Troponin-T Blood Test', price: 1238.10, quantity: 1 }
    ],
    tax: 261.90,
    discount: 0,
    total: 5500.00
  },
  {
    id: 'INV-2023-004',
    patientId: 'P-1006',
    patientName: 'Emily Davis',
    date: '28/10/2023',
    amount: 3250.00,
    status: 'Pending',
    items: [
      { description: 'Pediatric Specialist Consultation', price: 700.00, quantity: 1 },
      { description: 'MMR & Typhoid Booster Immunization', price: 2200.00, quantity: 1 },
      { description: 'Digital Ophthalmic & Ear Examination', price: 350.00, quantity: 1 }
    ],
    tax: 0,
    discount: 0,
    total: 3250.00
  },
  {
    id: 'INV-2023-005',
    patientId: 'P-1004',
    patientName: 'Michael Brown',
    date: '28/10/2023',
    amount: 9523.80,
    status: 'Paid',
    items: [
      { description: 'Orthopedic Consultation Fee', price: 1200.00, quantity: 1 },
      { description: 'Knee Joint Diagnostic X-Ray (4 Views)', price: 1500.00, quantity: 1 },
      { description: 'Custom Neoprene Knee Brace & Splinting', price: 6823.80, quantity: 1 }
    ],
    tax: 476.20,
    discount: 0,
    total: 10000.00
  },
  {
    id: 'INV-2023-006',
    patientId: 'P-1005',
    patientName: 'Jane Doe',
    date: '27/10/2023',
    amount: 450.00,
    status: 'Pending',
    items: [
      { description: 'Comprehensive Blood Glucose Profile (FBS & PPBS)', price: 450.00, quantity: 1 }
    ],
    tax: 0,
    discount: 0,
    total: 450.00
  },
  {
    id: 'INV-2023-007',
    patientId: 'P-1008',
    patientName: 'Kavita Menon',
    date: '30/10/2023',
    amount: 7800.00,
    status: 'Paid',
    items: [
      { description: 'Emergency Room Triage & Stat Care', price: 2500.00, quantity: 1 },
      { description: '24-Hour Holter Monitoring Attachment', price: 3500.00, quantity: 1 },
      { description: 'Serum Electrolyte & Renal Panel', price: 1800.00, quantity: 1 }
    ],
    tax: 390.00,
    discount: 0,
    total: 8190.00
  },
  {
    id: 'INV-2023-008',
    patientId: 'P-1010',
    patientName: 'Ananya Sharma',
    date: '27/10/2023',
    amount: 2800.00,
    status: 'Paid',
    items: [
      { description: 'Neurology Consultation (Dr. Rajesh Deshmukh)', price: 1800.00, quantity: 1 },
      { description: 'Digital EEG Brain Wave Screening', price: 1000.00, quantity: 1 }
    ],
    tax: 140.00,
    discount: 0,
    total: 2940.00
  }
];

export const mockPrescriptions: Prescription[] = [
  {
    id: 'RX-9901',
    date: '30/10/2023',
    patientId: 'P-1001',
    patientName: 'John Anderson',
    doctorId: 'D-101',
    doctorName: 'Dr. Sarah Chen',
    diagnosis: 'Essential Stage 1 Hypertension & Seasonal Allergic Rhinitis',
    chiefComplaint: 'Occasional morning headaches, nasal congestion and eye itching x 2 weeks',
    clinicalNotes: 'Blood pressure recorded at 138/86 mmHg. Pulse 74 bpm. Clear chest auscultation.',
    medicines: [
      {
        id: 'm1',
        name: 'Lisinopril',
        type: 'Tablet',
        strength: '10mg',
        dosage: '1 Tablet',
        frequency: 'Once Daily (Morning)',
        route: 'Oral',
        duration: '30 Days',
        quantity: '30',
        instructions: 'Take after light breakfast'
      },
      {
        id: 'm2',
        name: 'Loratadine',
        type: 'Tablet',
        strength: '10mg',
        dosage: '1 Tablet',
        frequency: 'Once Daily (Night)',
        route: 'Oral',
        duration: '14 Days',
        quantity: '14',
        instructions: 'Take at bedtime if allergy symptoms occur'
      },
      {
        id: 'm3',
        name: 'Fluticasone Propionate',
        type: 'Nasal Spray',
        strength: '50mcg/actuation',
        dosage: '1 Spray in each nostril',
        frequency: 'Twice Daily',
        route: 'Intranasal',
        duration: '15 Days',
        quantity: '1 Bottle',
        instructions: 'Shake bottle gently before use'
      }
    ],
    additionalInstructions: 'Maintain a low-sodium diet (<2g/day). Log BP readings every 3 days. Stay well-hydrated.',
    followUpRequired: true,
    followUpDate: '30/11/2023',
    followUpInstructions: 'Return for ambulatory blood pressure review.',
    status: 'Active',
    createdAt: '2023-10-30T10:00:00Z',
    updatedAt: '2023-10-30T10:00:00Z'
  },
  {
    id: 'RX-9902',
    date: '29/10/2023',
    patientId: 'P-1003',
    patientName: 'Robert Wilson',
    doctorId: 'D-102',
    doctorName: 'Dr. Michael Roberts',
    diagnosis: 'Coronary Artery Disease & Hyperlipidemia',
    chiefComplaint: 'Routine cardiac post-PTCA surveillance, mild exertional fatigue',
    clinicalNotes: 'ECG shows normal sinus rhythm. S1/S2 heard. No pedal edema.',
    medicines: [
      {
        id: 'm4',
        name: 'Atorvastatin',
        type: 'Tablet',
        strength: '40mg',
        dosage: '1 Tablet',
        frequency: 'Once Daily (Night)',
        route: 'Oral',
        duration: '90 Days',
        quantity: '90',
        instructions: 'Strictly after dinner'
      },
      {
        id: 'm5',
        name: 'Clopidogrel',
        type: 'Tablet',
        strength: '75mg',
        dosage: '1 Tablet',
        frequency: 'Once Daily (Morning)',
        route: 'Oral',
        duration: '90 Days',
        quantity: '90',
        instructions: 'Do not miss doses. Blood thinner protocol.'
      },
      {
        id: 'm6',
        name: 'Metoprolol Succinate',
        type: 'Tablet (ER)',
        strength: '25mg',
        dosage: '1 Tablet',
        frequency: 'Once Daily (Morning)',
        route: 'Oral',
        duration: '90 Days',
        quantity: '90',
        instructions: 'Monitor resting pulse'
      }
    ],
    additionalInstructions: 'Avoid heavy weight lifting. Walk 30 minutes daily on flat surface.',
    followUpRequired: true,
    followUpDate: '29/01/2024',
    followUpInstructions: 'Repeat Lipid Profile & Liver Function Test prior to next visit.',
    status: 'Active',
    createdAt: '2023-10-29T11:30:00Z',
    updatedAt: '2023-10-29T11:30:00Z'
  },
  {
    id: 'RX-9903',
    date: '28/10/2023',
    patientId: 'P-1006',
    patientName: 'Emily Davis',
    doctorId: 'D-103',
    doctorName: 'Dr. Ananya Iyer',
    diagnosis: 'Acute Viral Bronchiolitis & Fever',
    chiefComplaint: 'Barking cough, runny nose, low-grade fever x 2 days',
    clinicalNotes: 'Chest shows bilateral mild wheezing. Throat mildly hyperemic. SpO2 98% on room air.',
    medicines: [
      {
        id: 'm7',
        name: 'Paracetamol Pediatric Syrup',
        type: 'Syrup',
        strength: '120mg/5ml',
        dosage: '5 ml',
        frequency: 'Thrice Daily (As needed for fever > 100°F)',
        route: 'Oral',
        duration: '5 Days',
        quantity: '1 Bottle (60ml)',
        instructions: 'Give with calibrated dosing syringe'
      },
      {
        id: 'm8',
        name: 'Levosalbutamol Inhaler (with Spacers)',
        type: 'Inhaler',
        strength: '50mcg/puff',
        dosage: '2 Puffs',
        frequency: 'Every 8 Hours',
        route: 'Inhalation',
        duration: '5 Days',
        quantity: '1 Unit',
        instructions: 'Administer with pediatric face-mask spacer'
      }
    ],
    additionalInstructions: 'Warm saline gargles. Steam inhalation twice a day. Ensure adequate oral fluid intake.',
    followUpRequired: true,
    followUpDate: '02/11/2023',
    followUpInstructions: 'Review immediately if fast breathing or chest retraction is noticed.',
    status: 'Active',
    createdAt: '2023-10-28T09:15:00Z',
    updatedAt: '2023-10-28T09:15:00Z'
  },
  {
    id: 'RX-9904',
    date: '27/10/2023',
    patientId: 'P-1004',
    patientName: 'Michael Brown',
    doctorId: 'D-104',
    doctorName: 'Dr. Vikram Malhotra',
    diagnosis: 'Right Knee Grade 1 Medial Collateral Ligament (MCL) Sprain',
    chiefComplaint: 'Pain on medial aspect of knee following football tackle, swelling',
    clinicalNotes: 'McMurray negative, Lachman negative. Mild tenderness over MCL origin.',
    medicines: [
      {
        id: 'm9',
        name: 'Aceclofenac + Paracetamol + Serratiopeptidase',
        type: 'Tablet',
        strength: '100mg/325mg/15mg',
        dosage: '1 Tablet',
        frequency: 'Twice Daily',
        route: 'Oral',
        duration: '5 Days',
        quantity: '10',
        instructions: 'Must take strictly after full meals'
      },
      {
        id: 'm10',
        name: 'Pantoprazole',
        type: 'Tablet',
        strength: '40mg',
        dosage: '1 Tablet',
        frequency: 'Once Daily (Morning)',
        route: 'Oral',
        duration: '5 Days',
        quantity: '5',
        instructions: 'Take 30 minutes before breakfast'
      }
    ],
    additionalInstructions: 'R.I.C.E. protocol (Rest, Ice packing 15 mins x 4 times, Compression bandage, Elevation).',
    followUpRequired: true,
    followUpDate: '10/11/2023',
    followUpInstructions: 'Start isometric quadriceps exercises after 5 days.',
    status: 'Active',
    createdAt: '2023-10-27T14:45:00Z',
    updatedAt: '2023-10-27T14:45:00Z'
  },
  {
    id: 'RX-9905',
    date: '26/10/2023',
    patientId: 'P-1010',
    patientName: 'Ananya Sharma',
    doctorId: 'D-106',
    doctorName: 'Dr. Rajesh Deshmukh',
    diagnosis: 'Chronic Migraine Without Aura',
    chiefComplaint: 'Throbbing unilateral hemicranial headache with photophobia and nausea x 3 months',
    clinicalNotes: 'Normal cranial nerve examination. Fundoscopy normal. No focal neurological deficits.',
    medicines: [
      {
        id: 'm11',
        name: 'Flunarizine',
        type: 'Tablet',
        strength: '5mg',
        dosage: '1 Tablet',
        frequency: 'Once Daily (Night)',
        route: 'Oral',
        duration: '60 Days',
        quantity: '60',
        instructions: 'Prophylaxis: take consistently at night'
      },
      {
        id: 'm12',
        name: 'Naproxen + Domperidone',
        type: 'Tablet',
        strength: '500mg/10mg',
        dosage: '1 Tablet',
        frequency: 'SOS (At onset of acute attack)',
        route: 'Oral',
        duration: 'As needed',
        quantity: '10',
        instructions: 'Take immediately with water at first sign of headache'
      }
    ],
    additionalInstructions: 'Maintain headache diary. Avoid irregular sleep, skip meals, and caffeinated beverages.',
    followUpRequired: true,
    followUpDate: '26/12/2023',
    followUpInstructions: 'Evaluate headache attack frequency reduction.',
    status: 'Active',
    createdAt: '2023-10-26T16:00:00Z',
    updatedAt: '2023-10-26T16:00:00Z'
  }
];

export const mockMedicines = [
  { id: 'M-1', name: 'Paracetamol', type: 'Tablet', strength: '500mg' },
  { id: 'M-2', name: 'Amoxicillin + Clavulanic Acid', type: 'Tablet', strength: '625mg' },
  { id: 'M-3', name: 'Ibuprofen', type: 'Tablet', strength: '400mg' },
  { id: 'M-4', name: 'Cetirizine HCl', type: 'Tablet', strength: '10mg' },
  { id: 'M-5', name: 'Metformin Hydrochloride', type: 'Tablet', strength: '500mg' },
  { id: 'M-6', name: 'Atorvastatin Calcium', type: 'Tablet', strength: '20mg' },
  { id: 'M-7', name: 'Omeprazole', type: 'Capsule', strength: '20mg' },
  { id: 'M-8', name: 'Amlodipine Besylate', type: 'Tablet', strength: '5mg' },
  { id: 'M-9', name: 'Azithromycin', type: 'Tablet', strength: '500mg' },
  { id: 'M-10', name: 'Pantoprazole Sodium', type: 'Tablet', strength: '40mg' },
  { id: 'M-11', name: 'Telmisartan', type: 'Tablet', strength: '40mg' },
  { id: 'M-12', name: 'Montelukast Sodium + Levocetirizine', type: 'Tablet', strength: '10mg/5mg' },
  { id: 'M-13', name: 'Cefixime', type: 'Tablet', strength: '200mg' },
  { id: 'M-14', name: 'Lisinopril', type: 'Tablet', strength: '10mg' },
  { id: 'M-15', name: 'Metoprolol Tartrate', type: 'Tablet', strength: '50mg' },
  { id: 'M-16', name: 'Loratadine', type: 'Tablet', strength: '10mg' },
  { id: 'M-17', name: 'Aceclofenac + Paracetamol', type: 'Tablet', strength: '100mg/325mg' },
  { id: 'M-18', name: 'Flunarizine', type: 'Tablet', strength: '5mg' },
  { id: 'M-19', name: 'Glimepiride', type: 'Tablet', strength: '2mg' },
  { id: 'M-20', name: 'Doxycycline Hyclate', type: 'Capsule', strength: '100mg' }
];

export const mockServices = [
  { id: 'S-1', name: 'General Physician Consultation (OPD)', price: 500 },
  { id: 'S-2', name: 'Specialist Doctor Consultation', price: 1500 },
  { id: 'S-3', name: 'Complete Blood Count (CBC) with ESR', price: 450 },
  { id: 'S-4', name: 'Digital Chest X-Ray (PA View)', price: 850 },
  { id: 'S-5', name: 'Standard 12-Lead ECG / EKG', price: 600 },
  { id: 'S-6', name: 'Lipid Profile Comprehensive Panel', price: 750 },
  { id: 'S-7', name: 'Liver Function Test (LFT Panel)', price: 900 },
  { id: 'S-8', name: 'Routine Urine Analysis & Microscopy', price: 200 },
  { id: 'S-9', name: 'Fasting Blood Sugar (FBS Glucose)', price: 100 },
  { id: 'S-10', name: 'Post-Prandial Blood Sugar (PPBS)', price: 100 },
  { id: 'S-11', name: 'Glycated Hemoglobin (HbA1c)', price: 650 },
  { id: 'S-12', name: 'Thyroid Profile (Total T3, T4, TSH)', price: 800 },
  { id: 'S-13', name: 'Kidney Function Test (KFT / RFT)', price: 850 },
  { id: 'S-14', name: '2D Echocardiography (Echo Doppler)', price: 2500 },
  { id: 'S-15', name: 'Intravenous Injection / Infusion Admin', price: 150 },
  { id: 'S-16', name: 'Minor Surgical Dressing & Wound Care', price: 350 }
];
